# Generated by Django 3.0.8 on 2020-07-10 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='editorialBody',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_Name', models.CharField(max_length=100, null=True)),
                ('university', models.CharField(max_length=100, null=True)),
                ('topic', models.CharField(max_length=100, null=True)),
                ('serial_no', models.CharField(max_length=100, null=True)),
                ('editorial_body', models.CharField(choices=[('Nadia Islam', 'Nadia Islam'), ('Laiba Tasnia', 'Laiba Tasnia'), ('Jahid Oyon', 'Jahid Oyon'), ('Anika Nargis', 'Anika Nargis'), ('Nusrat Meem', 'Nusrat Meem'), ('Mehenaj', 'Mehenaj'), ('Kheya', 'Kheya')], default='Nadia Islam', max_length=100)),
            ],
        ),
    ]
